### ISSUE TITLE
problem with FIPS 

### ISSUE THREAD

**Issue by petermchale** [brj0/mepylome#1]
```
(.venv) [u6018199@father *PE* methylation-tools]$mepylome --tutorial

                             _
                            | |
  _ __ ___   ___ _ __  _   _| | ___  _ __ ___   ___
 | '_ ` _ \ / _ \ '_ \| | | | |/ _ \| '_ ` _ \ / _ \
 | | | | | |  __/ |_) | |_| | | (_) | | | | | |  __/
 |_| |_| |_|\___| .__/ \__, |_|\___/|_| |_| |_|\___|
                | |     __/ |
                |_|    |___/


Starting Methylation Analysis...

Downloading IDAT's: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:12<00:00,  3.10it/s]
Downloading IDAT's: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  4.30it/s]
12:30:03 [guess_annotation_file] Searching for annotation file...
12:30:03 [guess_annotation_file] Found annotation file: /uufs/chpc.utah.edu/common/HIPAA/u6018199/Documents/mepylome/tutorial/tutorial_analysis/annotation.csv
12:30:03 [MethylAnalysis] Try to import cbseg or linear_segment...
12:30:03 [CNV] **Warning**: Segmentation won't be calculated due to missing 'linear_segment' resp. 'cbseg' package. See documentation.
Traceback (most recent call last):
  File "/scratch/ucgd/lustre-labs/quinlan/u6018199/methylation-tools/.venv/bin/mepylome", line 8, in <module>
    sys.exit(start_mepylome())
             ^^^^^^^^^^^^^^^^
  File "/scratch/ucgd/lustre-labs/quinlan/u6018199/methylation-tools/.venv/lib/python3.11/site-packages/mepylome/analysis/cli.py", line 191, in start_mepylome
    methyl_analysis = MethylAnalysis(**cli_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/ucgd/lustre-labs/quinlan/u6018199/methylation-tools/.venv/lib/python3.11/site-packages/mepylome/analysis/methyl.py", line 836, in __init__
    self._set_upload_dir()
  File "/scratch/ucgd/lustre-labs/quinlan/u6018199/methylation-tools/.venv/lib/python3.11/site-packages/mepylome/analysis/methyl.py", line 1025, in _set_upload_dir
    upload_hash_key = input_args_id(
                      ^^^^^^^^^^^^^^
  File "/scratch/ucgd/lustre-labs/quinlan/u6018199/methylation-tools/.venv/lib/python3.11/site-packages/mepylome/dtypes/cache.py", line 181, in input_args_id
    hasher = hashlib.md5()
             ^^^^^^^^^^^^^
ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
(.venv) [u6018199@father *PE* methylation-tools]$
```

Operating system: 

```
(.venv) [u6018199@father *PE* methylation-tools]$lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              128
On-line CPU(s) list: 0-127
Thread(s) per core:  2
Core(s) per socket:  64
Socket(s):           1
NUMA node(s):        4
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7702P 64-Core Processor
Stepping:            0
CPU MHz:             1996.136
BogoMIPS:            3992.27
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            16384K
NUMA node0 CPU(s):   0-15,64-79
NUMA node1 CPU(s):   16-31,80-95
NUMA node2 CPU(s):   32-47,96-111
NUMA node3 CPU(s):   48-63,112-127
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sme sev sev_es
```

Possibly useful: 
https://chatgpt.com/share/67325c46-ff68-8009-bbe2-f5e72c47a165

**Comment by petermchale** [comment]
`mepylome --tutorial` works on my Apple M2 Pro.

**Comment by brj0** [comment]
In FIPS-compliant Python builds, MD5 is disallowed. I replaced it with Blake2b (mepylome version 0.6.2)—should work now.
